#!/usr/bin/env python3
"""Wrap generated sphinxpress page bodies in Liquid raw tags for Jekyll 3."""

from __future__ import annotations

from pathlib import Path

GENERATED_MARKER = "<!-- GENERATED by sphinxpress. Do not edit by hand. -->"
RAW_START = "{% raw %}"
RAW_END = "{% endraw %}"


def wrap_page(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    if GENERATED_MARKER not in text or RAW_START in text:
        return
    text = text.replace(
        GENERATED_MARKER + "\n",
        GENERATED_MARKER + "\n" + RAW_START + "\n",
        1,
    )
    path.write_text(text.rstrip() + "\n" + RAW_END + "\n", encoding="utf-8")


def main() -> None:
    for path in Path("tools").glob("*/*.md"):
        wrap_page(path)


if __name__ == "__main__":
    main()
